@id = d50a20c7-74b2-46cb-8f51-6b1b73674870
@userId = 5bd2845f-3537-4d33-b06a-224bcb7164fd
@eventId = 5d3a32c3-e8f3-4593-bfae-bfd797ae68d1

###
GET http://localhost:3333/tickets/{{id}}

###
POST http://localhost:3333/tickets
Content-Type: application/json

{
  "userId": "{{userId}}",
  "eventId": "{{eventId}}"
}

###
GET http://localhost:3333/tickets/user/{{userId}}
Content-Type: application/json