@id = 
@userId = 4ea40928-8e2a-4f87-843f-43f97d1699c5
@eventId = 08db1be5-e2df-43b1-8592-a9b0b98f64a9

###
GET http://localhost:3333/tickets/{{id}}

###
POST http://localhost:3333/tickets
Content-Type: application/json

{
  "userId": "{{userId}}",
  "eventId": "{{eventId}}"
}

###
PATCH http://localhost:3333/tickets/{{id}}
Content-Type: application/json

{
  "name": "Event updated",
  "capacity": 200
}

###
DELETE http://localhost:3333/tickets/{{id}}